# Generated by Django 2.1.7 on 2019-03-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_category_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
    ]
