# Generated by Django 2.1.7 on 2019-03-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_remove_category_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.Category')),
            ],
        ),
    ]
