# Generated by Django 2.1.7 on 2019-04-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_categorycount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycount',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryCount',
        ),
    ]
