# Generated by Django 2.1.7 on 2019-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0006_auto_20190420_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.EmailField(default='admin@admin.com', max_length=254),
        ),
    ]
