# Generated by Django 2.1.7 on 2019-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0009_auto_20190601_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_total',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
